Repository DSACMS/metrics, pull requests merged in 2024-10, with the labels that each got.

#242 added predominant language graph to repo pages
  scripts/gen_graphs.py
  templates/repo_report_template.md
Labels: enhancement, front-end

#250 Create Graph for DRYness Percentage
  scripts/gen_graphs.py
  templates/repo_report_template.md
Labels: enhancement

#255 Create Graph for Libyears Metric
  scripts/gen_graphs.py
  templates/org_report_template.md
  templates/repo_report_template.md
Labels: enhancement

#257 Add language summary dk
  .github/workflows/codeql.yml
  .github/workflows/scorecard.yml
  scripts/gen_graphs.py
  templates/repo_report_template.md
Labels: enhancement, front-end

#258 Add Missing Value Formatting Methods
  scripts/gen_graphs.py
Labels: front-end

#254 Added Age of Project to Frontend
  app/site/_layouts/repo-report.liquid
Labels: enhancement, front-end

#259 Add cost estimates dk
  scripts/gen_graphs.py
  templates/repo_report_template.md
Labels: enhancement, front-end

#261 Display Total Libyears in Libyear Graph Title
  scripts/gen_graphs.py
Labels: enhancement

#265 Add time estimates dk
  scripts/gen_graphs.py
  templates/repo_report_template.md
Labels: enhancement, front-end

#267 Add individual contributors graph
  scripts/gen_graphs.py
  templates/repo_report_template.md
Labels: enhancement, front-end

#273 Patch Libyear Graph to Reverse Order
  scripts/gen_graphs.py
Labels: bug

#270 Development: Added script to test prod on dev
  app/.eleventy.js
  app/package.json
  app/postcss.config.js
  app/rollup.config.mjs
  app/site/_data/site.js
  app/site/projects.liquid
  app/src/js/projects.js
  app/src/js/templates.js
Labels: enhancement, front-end

#276 Add Missing Public DSACMS Repositories
  scripts/_metadata/projects_tracked.json
Labels: enhancement
