Repository DSACMS/metrics, pull requests merged in 2025-03, with the labels that each got.

#340 Refactor org reports page
  app/src/css/style.css
  templates/org_report_template.md
  templates/repo_report_template.md
Labels: front-end, metrics

#342 Refactor modal
  app/site/_includes/modal-content.liquid
  app/src/js/modal.js
Labels: enhancement, front-end, javascript, metrics

#344 Fix-stat-spacing
  app/site/_layouts/org-report.liquid
  app/site/_layouts/repo-report.liquid
  app/src/css/style.css
Labels: enhancement, front-end, metrics

#337 Update projects_tracked.json
  scripts/_metadata/projects_tracked.json
Labels: metrics
